import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Legal Document Search",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased `}>
        <header>
            {/* <Header /> */}
          </header>
          <main className="min-h-full bg-gradient-to-br from-gray-50 to-gray-100" style={{ minHeight: 'calc(100vh - 84px)' }}>
            {children}
          </main>
          <footer>
            <Footer />
          </footer>
      </body>
    </html>
  );
}
